# Generated by Django 2.1.1 on 2019-08-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Alumini', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AluminiHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_info', models.TextField(blank=True, max_length=500)),
                ('fb_link', models.URLField(blank=True)),
                ('insta_link', models.URLField(blank=True)),
                ('twitter_link', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contactus',
            name='user_name',
            field=models.CharField(max_length=50),
        ),
    ]
