# Generated by Django 2.1.1 on 2019-08-10 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('RegisterApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenderField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HigherEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_college', models.CharField(blank=True, max_length=100, null=True)),
                ('user_college_state', models.CharField(blank=True, max_length=50, null=True)),
                ('user_college_city', models.CharField(blank=True, max_length=50, null=True)),
                ('user_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                                  to='RegisterApp.CourseName')),
            ],
        ),
        migrations.CreateModel(
            name='HigherStudies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostelName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('company_city', models.CharField(blank=True, max_length=100, null=True)),
                ('company_state', models.CharField(blank=True, max_length=100, null=True)),
                ('work_exp_years', models.IntegerField(blank=True, max_length=2, null=True)),
                ('work_exp_months', models.IntegerField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PassoutBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(blank=True, max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_add', models.TextField(blank=True, max_length=100, null=True)),
                ('school_state', models.CharField(blank=True, max_length=50, null=True)),
                ('school_district', models.CharField(blank=True, max_length=50, null=True)),
                ('school_city', models.CharField(blank=True, max_length=50, null=True)),
                ('school_hostel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                                    to='RegisterApp.HostelName')),
            ],
        ),
        migrations.CreateModel(
            name='UserAddr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_addr', models.TextField(blank=True, max_length=100, null=True)),
                ('user_state', models.CharField(blank=True, max_length=50, null=True)),
                ('user_district', models.CharField(blank=True, max_length=50, null=True)),
                ('user_city', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='count',
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='middle_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='highereducation',
            name='user_high_education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='RegisterApp.HigherStudies'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_addr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='RegisterApp.UserAddr'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='RegisterApp.PassoutBatch'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='RegisterApp.GenderField'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_high_edu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='RegisterApp.HigherEducation'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='RegisterApp.JobDescription'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    to='RegisterApp.SchoolAdd'),
        ),
    ]
