# Generated by Django 2.1.1 on 2019-08-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('RegisterApp', '0002_auto_20190810_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdescription',
            name='work_exp_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobdescription',
            name='work_exp_years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passoutbatch',
            name='title',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
